# Generated by Django 2.2 on 2019-06-24 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True
    atomic=False

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreakdownMaintenaceWorkRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_by', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Electrical', 'Electrical'), ('Mechanical', 'Mechanical'), ('Automotive', 'Automotive'), ('Plumbing', 'Plumbing'), ('Carpentry', 'Carpentry')], max_length=20)),
                ('down_time', models.TimeField()),
                ('labour_time', models.TimeField()),
                ('team', models.CharField(max_length=24)),
                ('responsible', models.CharField(max_length=24)),
                ('duration', models.TimeField()),
                ('consumables_required', models.TextField(max_length=256)),
                ('resolved_by_vendor', models.BooleanField(default=False)),
                ('vendor', models.CharField(max_length=255)),
                ('service_order_ref', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreventativeMaintenaceWorkRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_by', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Electrical', 'Electrical'), ('Mechanical', 'Mechanical'), ('Automotive', 'Automotive'), ('Plumbing', 'Plumbing'), ('Carpentry', 'Carpentry')], max_length=20)),
                ('team', models.CharField(max_length=24)),
                ('responsible', models.CharField(max_length=24)),
                ('duration', models.TimeField()),
                ('consumables_required', models.TextField(max_length=256)),
                ('resolved_by_vendor', models.BooleanField(default=False)),
                ('vendor', models.CharField(max_length=255)),
                ('service_order_ref', models.CharField(max_length=255)),
                ('scheduled_date', models.DateField()),
                ('down_time', models.TimeField()),
                ('labour_time', models.TimeField()),
                ('tasks', models.CharField(max_length=264)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolver', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], max_length=32)),
                ('approved_by', models.CharField(max_length=32)),
                ('approved_date', models.DateField()),
                ('consumables_used', models.TextField()),
                ('breakdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenanceapp.BreakdownMaintenaceWorkRequest')),
                ('planned_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenanceapp.PreventativeMaintenaceWorkRequest')),
            ],
        ),
    ]
