# Generated by Django 2.2 on 2019-06-26 03:23

from django.db import migrations


class Migration(migrations.Migration):
    atomic=False

    dependencies = [
        ('maintenanceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breakdownmaintenaceworkrequest',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='preventativemaintenaceworkrequest',
            old_name='name',
            new_name='description',
        ),
    ]
