# Generated by Django 2.2 on 2019-06-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic=False

    dependencies = [
        ('maintenanceapp', '0002_auto_20190626_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdownmaintenaceworkrequest',
            name='description',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='preventativemaintenaceworkrequest',
            name='description',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
