# Generated by Django 2.2 on 2019-06-26 03:46

from django.db import migrations


class Migration(migrations.Migration):
    atomic=False

    dependencies = [
        ('maintenanceapp', '0003_auto_20190626_0524'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BreakdownMaintenaceWorkRequest',
            new_name='BreakdownMaintenanceWorkRequest',
        ),
    ]
