# Generated by Django 2.2 on 2019-06-26 04:07

from django.db import migrations


class Migration(migrations.Migration):
    atomic=False

    dependencies = [
        ('maintenanceapp', '0004_auto_20190626_0546'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreventativeMaintenaceWorkRequest',
            new_name='PreventativeMaintenanceWorkRequest',
        ),
    ]
