# Generated by Django 2.2 on 2019-07-01 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenanceapp', '0005_auto_20190626_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desription', models.TextField()),
                ('start_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('frequency', models.CharField(max_length=24)),
                ('duration', models.DurationField()),
                ('category', models.CharField(choices=[('electrical', 'Electrical'), ('mechanical', 'Mechanical'), ('automotive', 'Automotive'), ('plumbing', 'Plumbing'), ('carpentry', 'Carpentry'), ('hydraulics', 'Hydraulics'), ('pneumatics', 'Pneumatics')], max_length=255)),
                ('resolver', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='breakdownmaintenanceworkrequest',
            name='down_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='breakdownmaintenanceworkrequest',
            name='duration',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='breakdownmaintenanceworkrequest',
            name='labour_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='preventativemaintenanceworkrequest',
            name='duration',
            field=models.TimeField(null=True),
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenanceapp.MaintenanceChecklist')),
            ],
        ),
    ]
