from django.urls import path
from . import views

app_name = 'maintenanceapp'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('maintenance-create/', views.BreakdownMaintenanceWorkView.as_view(), 
        name='maintenance-create'),
    path('maintenance-record-create/', views.MaintenanceRecordView.as_view(), 
        name='maintenance-record-create'),
    path('preventative-create/', views.PreventativeMaintenaceWorkView.as_view(),
        name='preventative-create'),
    path('checklist-create/', views.MaintenanceChecklistCreate.as_view(),
        name='checklist-create'),
    path('checklistitem-create/', views.ChecklistItemCreate.as_view(),
        name='checklistitem-create'),
    path('maintenance-detail/<int:pk>', 
        views.BreakdownMaintenanceWorkDetailView.as_view(),
        name='maintenance-detail'),
    path('maintenance-record-detail/<int:pk>', 
        views.MaintenanceRecordDetailView.as_view(),    
        name='maintenance-record-detail'),
    path('preventative-detail/<int:pk>', 
        views.PreventativeMaintenanceWorkDetailView.as_view(),
        name='preventative-detail'),
    path('checklist-detail/<int:pk>',views.MaintenanceChecklistDetail.as_view(),
        name='checklist-detail'),
    path('checklistitem-detail/<int:pk>',views.ChecklistItemDetail.as_view(),
        name='checklistitem-detail'),
    path('maintenance-update/<int:pk>',
        views.BreakdownMaintenanceWorkUpdateView.as_view(),
        name='maintenance-update'),
    path('maintenance-record-update/<int:pk>',
        views.MaintenanceRecordUpdateView.as_view(),
        name='maintenance-record-update'),
    path('preventative-update/<int:pk>',
        views.PreventativeMaintenanceWorkUpdateView.as_view(),
        name='preventative-update'),
    path('checklist-update/<int:pk>',views.MaintenanceChecklistUpdate.as_view(),
        name='checklist-update'),
    path('checklistitem-update/<int:pk>',views.ChecklistItemUpdate.as_view(),
        name='checklistitem-update'),
    path('maintenance-list',views.BreakdownMaintenanceWorkRequestList.as_view(),
        name='maintenance-list'),
    path('maintenance-record-list',views.MaintenanceRecordlist.as_view(),
        name='maintenance-record-list'),
    path('preventative-list',views.PreventativeMaintenanceWorklist.as_view(),
        name='preventative-list'),
    path('checklist-list',views.MaintenanceChecklistList.as_view(),
        name='checklist-list'),
    path('checklistitem-list',views.ChecklistItemList.as_view(),
        name='checklistitem-list'),
    path('maintenance/<int:pk>/delete', 
        views.BreakdownMaintenanceWorkDelete.as_view(),
        name='maintenance-delete'),
    path('maintenance-record/<int:pk>/delete', 
        views.MaintenanceRecordDelete.as_view(),
        name='maintenance-record-delete'),
    path('preventative/<int:pk>/delete', 
        views.PreventativeMaintenanceDelete.as_view(),
        name='preventative-delete'),
    path('checklist/<int:pk>/delete', views.MaintenaceChecklistDelete.as_view(),
        name='checklist-delete'),
    path('checklistitem/<int:pk>/delete', views.ChecklistItemDelete.as_view(),
        name='checklistitem-delete'),
]